### ISSUE TITLE
Remember playback speed

### ISSUE THREAD

**Issue by zeref-dragneel** [zer0-x/video-speed-setter#7]
I think it would be very nifty if this extension could be configured to remember and automatically apply the playback speed that was last used. This could either be done globally, site-wide (as in specific to, say, Youtube) or per page/URL (although personally, I'd find site-wide most useful)

**Comment by zefr0x** [comment]
It seems like a good idea at first sight, but in fact its implementation has many bad aspects.


1. We will need to run some  JavaScript code on every page without the user's request, whether there was a video in the page or not. This may be useful for figurprinting and may cause some pages to be corrupted, although the last one is less likely, this will harm the user experience and the privacy.

2. Currently, the way to speed up videos when using the keyboard shortcuts is relative as we don't set a specific speed but actually we increase the current one. Therefore, if we want to store the value of the current speed to be used later, we may need to request some information from the page itself, and this requires access to more permissions from the browser, and dealing with these matters leads to security vulnerabilities.

I want to keep the extension away from any security and privacy issues, so if you have any idea to implement this securely that would be great, other than that this feature will not be implemented.

Personally, I use [invidious](https://github.com/iv-org/invidious) as an alternative to the youtube interface when watching via the browser and it does this work for me.

**Comment by zeref-dragneel** [comment]
Thank you for the information
